# Generated by Django 3.2 on 2022-09-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(default=1, upload_to='photos/tienda/producto', verbose_name='Imagen Producto'),
            preserve_default=False,
        ),
    ]
