# Generated by Django 3.2 on 2022-09-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_imagen_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='imagen_tienda',
            field=models.ImageField(default=1, upload_to='photos/tienda/local', verbose_name='Imagen Tienda'),
            preserve_default=False,
        ),
    ]
